version: "3.8"
services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    restart: always
  warehouse:
    image: postgres:13-buster
    hostname: warehouse
    environment:
      POSTGRES_USER: dwh
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dwh
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dwh"]
      interval: 10s
      retries: 3
    restart: always