
version: 2

models:
  - name: fruit_purchases_a
    description: "Fruit purchases"
    columns:
      - name: product
        description: "The type of purchase"
        tests:
          - accepted_values:
              values: ['apple', 'banana', 'orange']
  - name: users_incremental
    description: "List of users added"
    columns:
      - name: user
        description: "Unique identifier"
        tests:
          - not_null
          - relationships:
              to: ref('fruit_purchases_a')
              field: user